language: node_js
node_js:
  - "9"

branches:
  only:
  - master

install:
  - npm i --progress --no-audit

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Build & Deploy
      script: npm run build
      deploy: &surge
        provider: surge
        skip_cleanup: true
        project: ./build/
        domain: sergeistralenia.surge.sh