apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-ss
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-service
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379