name: default

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 9.x
        uses: actions/setup-node@v1
        with:
          node-version: 9.x
      - run: npm install --progress --no-audit
      - run: npm lint
      - run: npm run build
      - run: npm run gh-deploy
